[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flower-qml-project"
version = "1.0.0"
description = "Federated Learning with PennyLane"
license = {file = "LICENSE"}
dependencies = [
    "flwr[simulation]>=1.28.0",
    "flwr-datasets[vision]>=0.6.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "pennylane==0.41.1",
    "autoray>=0.6,<0.7",
]

[tool.hatch.build.targets.wheel]
packages = [
    "evaluation",
    "loaders",
    "models",
    "trainer"
]

[tool.hatch.build]
packages = ["trainer", "models", "loaders", "evaluation"]

[tool.flwr.app]
publisher = "guiaraujo"
fab-include = [
    "evaluation/**/*.py",
    "loaders/**/*.py",
    "models/**/*.py",
    "trainer/**/*.py",
]

[tool.flwr.app.components]
serverapp = "trainer.server_app:app"
clientapp = "trainer.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 10
batch-size = 32
local-epochs = 2
learning-rate = 0.001
fraction-fit = 1.0
fraction-evaluate = 0.5

# Quantum circuit configuration
n-qubits = 4
n-layers = 3
model = "CQC"

[tool.flwr.federation]
mode = "simulation"

[tool.flwr.federation.simulation]
num-supernodes = 2